# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'AnnouncementPlus', '0001_initial'), (b'AnnouncementPlus', '0002_auto_20161113_1644'), (b'AnnouncementPlus', '0003_auto_20161118_1711'), (b'AnnouncementPlus', '0004_auto_20161118_1723'), (b'AnnouncementPlus', '0005_auto_20161127_1902'), (b'AnnouncementPlus', '0006_auto_20161127_1908'), (b'AnnouncementPlus', '0007_auto_20161202_2330'), (b'AnnouncementPlus', '0008_auto_20161202_2354')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=64)),
                ('pwdHash', models.CharField(max_length=64)),
                ('pwdSalt', models.CharField(max_length=16)),
                ('token', models.CharField(blank=True, default=b'', max_length=64)),
                ('tokenExpirationTime', models.DateTimeField(blank=True, default=b'2000-01-01 00:00:00+00:00')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=b'', max_length=128)),
                ('summary', models.CharField(blank=True, default=b'', max_length=4096)),
                ('detail', models.CharField(blank=True, default=b'', max_length=65536)),
                ('pushDate', models.DateField(default=b'2000-01-01')),
                ('isEvent', models.BooleanField(default=False)),
                ('eventTime', models.DateTimeField(default=b'2000-01-01 00:00:00+00:00')),
                ('locationName', models.CharField(blank=True, default=b'', max_length=64)),
                ('locationDesc', models.CharField(blank=True, default=b'', max_length=256)),
                ('locationLat', models.FloatField(blank=True, default=0.0)),
                ('locationLng', models.FloatField(blank=True, default=0.0)),
                ('foodProvided', models.BooleanField(default=False)),
                ('hostFirstName', models.CharField(default=b'', max_length=64)),
                ('hostLastName', models.CharField(blank=True, default=b'', max_length=64)),
                ('hostOrganization', models.CharField(blank=True, default=b'', max_length=64)),
                ('hostEmail', models.CharField(default=b'', max_length=64)),
                ('hostPhone', models.CharField(blank=True, default=b'', max_length=64)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'Unapproved', b'Unapproved'), (b'Approved', b'Approved'), (b'Declined', b'Declined')], default=b'Unapproved', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=64)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessCodeHash', models.CharField(default=b'', max_length=64)),
                ('accessCodeSalt', models.CharField(default=b'', max_length=16)),
                ('firstName', models.CharField(default=b'', max_length=64)),
                ('lastName', models.CharField(blank=True, default=b'', max_length=64)),
                ('organization', models.CharField(blank=True, default=b'', max_length=64)),
                ('email', models.CharField(blank=True, default=b'', max_length=64)),
                ('phone', models.CharField(blank=True, default=b'', max_length=64)),
                ('token', models.CharField(blank=True, default=b'', max_length=64)),
                ('tokenExpirationTime', models.DateTimeField(blank=True, default=b'2000-01-01 00:00:00+00:00')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='createUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AnnouncementPlus.User'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AnnouncementPlus.Location'),
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=b'', max_length=64)),
                ('lastName', models.CharField(blank=True, default=b'', max_length=64)),
                ('organization', models.CharField(blank=True, default=b'', max_length=64)),
                ('email', models.CharField(blank=True, default=b'', max_length=64)),
                ('phone', models.CharField(blank=True, default=b'', max_length=64)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='attendants',
            field=models.ManyToManyField(to=b'AnnouncementPlus.Attendant'),
        ),
    ]
