# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnouncementPlus', '0002_auto_20161207_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
